/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./../src/components/layout/AppBar.vue')['default']
    AppBreadcrumbs: typeof import('./../src/components/layout/AppBreadcrumbs.vue')['default']
    AppDrawer: typeof import('./../src/components/layout/AppDrawer.vue')['default']
    AppLanguage: typeof import('./../src/components/layout/AppLanguage.vue')['default']
    AppMain: typeof import('./../src/components/layout/AppMain.vue')['default']
    AppThemeToggle: typeof import('./../src/components/layout/AppThemeToggle.vue')['default']
    AppUserMenu: typeof import('./../src/components/layout/AppUserMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
